# STOCK STRUCTURE AND DISTRIBUTION  

Fraser River Pink Salmon predominantly spawn in the lower portion of the Fraser Basin, below the Fraser Canyon and Hells Gate (Figure \@ref(fig:fig-map)). 
However, there is a large component of the stock that returns to the Thompson River and the Seton-Anderson complex. 
Before the slide at Hells Gate in 1914, most of the Fraser River Pink Salmon run returned and spawned in the upper Fraser River [@pessInfluencePopulationDynamics2012]. 
Although there is a lack of abundance data at the tributary level in recent decades for Fraser Pink Salmon, assessment observations from other species have persistently noted Pink Salmon in the Quesnel, Chilcotin, and the Nechako Rivers. 
In 2019, DFO was alerted to a landslide in the middle Fraser near Big Bar. 
Pink Salmon were noted as being among the species delayed in their upstream migration by the slide. 
Slide mitigation efforts have largely been successful and Pink Salmon were in the Nechako River upstream of the slide in 2023 (R. Martin, DFO, Kamloops, British Columbia, pers. comm.).  


Fraser Pink Salmon are assumed to comprise a single Conservation Unit [@holtbyConservationUnitsPacific2008]. 
However, there is some evidence for life history differences between Pinks that spawn above and below Hells Gate. 
For example, Pink Salmon from above Hells Gate have higher maximum swimming speeds, allowing them to negotiate the Hells Gate rapids [@rickerHistoryPresentState1989; @williams1983EarlyRun1986], which may be based on genetic differences [@beachamVariationBodySize1988]. 
In addition, Pink Salmon returning to areas upstream and downstream of Hells Gate have slightly different return timing as evidenced through recent sampling for genetic stock identification in lower Fraser test fisheries (S. Latham, PSC, Vancouver, British Columbia, pers. comm). 
The differences suggest that there may be more genetic and life history differences between spawning populations above and below Hells Gate than previously thought. 
The Committee on the Status of Endangered Wildlife in Canada (COSEWIC) is currently reviewing Pink Salmon population structure in Canada including in the Fraser River (B. Leaman, COSEWIC, Duncan, British Columbia, pers. comm.).  
