# DISCUSSION  

## SUMMARY OF KEY FINDINGS  

In this working paper we briefly review our current understanding of Fraser River Pink salmon stock structure and distribution, assessment history, and ecosystem and climate factors affecting the stock. 
We then fit a state-space spawner-recruitment model to available to data to characterize stock dynamics, and derive estimates of biological benchmarks to assess stock status. 
Lastly, we developed a simple closed-loop simulation model based on recent productivity estimates to quantify future expected biological and fishery performance of the current, an illustrative alternative HCR, and a no fishing scenario.  

Odd year Fraser Pinks spawn throughout the Fraser Basin and comprise a single Conservation Unit though there is evidence of life history differences between populations that spawn in the upper and lower Fraser River (above and below Hells Gate). 
Landslides have occurred throughout the Fraser causing migratory impediments that have impacted returning adult salmon at different periods with the most notable being Hells Gate in 1914 and more recently the Big Bar Landslide in 2018/19. 
Fraser Pink salmon marine survival is associated with sea-surface temperatures during early marine life, spring bloom timing and the North Pacific Current, all of which index physical and biological oceanographic conditions that likely affect prey production, transport, and availability during early marine life. 
Adult body size has declined over time, coincident with increasing abundances of salmon in the North Pacific, which has the potential to impact reproductive output as fecundity scales with female size.  

We found that the Fraser Pink stock is moderately productive with intrinsic productivity ($\alpha$) estimated to be `r bench.par.table[5,1]` (`r bench.par.table[5,2]`-`r bench.par.table[5,3]` recruits per spawner) and equilibrium stock size $S_{EQ}$ equal to `r benchmarks[4,1]`m (`r benchmarks[4,2]`-`r benchmarks[4,3]`m). 
We estimated the USR of 80% $S_{MSY}$ to be `r benchmarks[2,1]`m (`r benchmarks[2,2]`-`r benchmarks[2,3]`m), and the Limit Reference Point $S_{gen}$ to be `r benchmarks[1,1]`m (`r benchmarks[1,2]`-`r benchmarks[1,3]`m). 
The most recent (2023) observation of spawner abundance for Fraser Pink salmon is 9.58m which is well above the 90th percentile of the USR estimate suggesting the stock is in a “healthy” state which is consistent with a formal Wild Salmon Policy status assessment that has assessed the stock as in the “green” Wild Salmon Policy status zone with high confidence.  

A time-varying productivity model used to condition the forward simulation showed that productivity of Fraser Pinks has been declining since the 1980s, roughly coincident with onset of decline in average size of returning adults. Productivity in recent years is nearly half of what it was at it's peak in the 1980s. 

We found that the existing HCR for Fraser Pinks has a very low probability (`r perf.metrics[1,3]`%) of the stock falling below the Limit Reference Point, and a relatively high probability (`r perf.metrics[1,4]`) of spawner abundance being above the USR, over the next 10 years. 
Assuming fisheries fully utilize allowable catch, which may not be the case if the Pink fishery is constrained, for example, to limit impacts on non-target species, average annual catch is projected to 10.3m over the same time period. 
Assessment of an illustrative alternative HCR which is strictly compliant with DFO’s Precautionary Approach Framework had similar biological performance with slightly less catch.
A no-fishing HCR showed about 5% more simulations being above the USR and not much change in the percentage of stocks falling below the LRP (only 0.3% less risky). 

The robustness test of the current HCR suggest that if stock productivity were to decline sharply and/or be depressed for a prolonged period the current HCR would have ~5% greater probability of falling below the LRP,  ~14% greater probability of falling below USR in "amber" zone, and ~7m less fish caught than under the baselien scenario. 
The alternative, strictly PA compliant, HCR performed relatively worse than the current HCR under the robistness test, possibly due to the higher allowable exploitation rates at intermediate run sizes under this HCR. 
To mitigate these risks, one option could be to use a dynamic version of our alternate HCR, where the removal reference $U_{MSY}$ changes in relation to current estimates of time-varying productivity.  


## CAVEATS AND ASSUMPTIONS  

The performance measures from the forward simulations should be interpreted with caution for several reasons. 
First, our performance measures are calculated across the full five generations of the simulations and so do not capture finer, shorter term performance as shown in the trajectory figures (e.g. the relatively higher median catch in the current HCR could be due to a short term gain in catch in 2025). 
Second, we made the simplifying assumption that forecast error and outcome uncertainty were lognormally and normally distributed across run sizes, respectively. 
When run sizes are forecast to be low, there may not be additional commercial fishing data to support in season adjustments [@hagueImprovementsFraserRiver2022]. 
Small sample sizes in Pink catch could also cascade uncertainty through the various methods to estimate stock size: test fisheries, CPUE analyses, genetic stock identification, and the hydroacoustic program [@hagueMovingTargetsAssessing2021]. 
Low sample size and fishing effort can exacerbate forecast error at low run size, therefore potentially violating our assumption forecast error is consistent among run sizes. 
Second, outcome uncertainty (i.e., how close you are toward the target exploitation rate) may be lower than expected for practical management reasons (e.g., reducing Pink fishing effort to protect at-risk Sockeye populations). 
In addition, the price of Pink salmon has been so low in recent years that it may not be economically feasible for commercial fishers to operate. 
Taken together, these reasons for reductions in fishing effort may make the shape of true outcome uncertainty right skewed, since fisheries are typically under harvesting their total allowable catch
Therefore, it is important to consider the values in table \@ref(tab:tab-HCR-performance) as relative performance measures and not absolutes; catches may not be realized due to various management considerations.  


## EXCEPTIONAL CIRCUMSTANCES OR ASSESSMENT TRIGGERS FOR THE STOCK  

Exceptional circumstances are assessment triggers intended to proactively identify conditions and/or circumstances that may represent a substantial departure from those under which the advice in this assessment was developed. 
In addition to routine re-assessment every 2 generations to ensure stock status can be updated and captures contemporary fishery and biological processes, we recommend a re-assessment be triggered if any of the following occur:   

- Stock productivity changes drastically, where the median estimate of time-varying productivity (annual Ricker $\alpha$) falls outside the 50th percentile (i.e. `r recent.a.50s[[1]]`-`r recent.a.50s[[2]]`), of the 3 generation median productivity used to condition our forward simulation;    

- New information becomes available that results in changes to the historical time-series of spawner abundance and catches used in this working paper; and

- New information becomes available that results in changes to our understanding of stock-structure (e.g., the current Conservation Unit is split into two) and/or major drivers of stock dynamics. 

Lastly, should Fisheries Management consider changes to the existing HCR and/or revisions to the fishery objectives against which it needs to be evaluated, then the assessment model and closed-loop simulation framework we describe should be revisited to ensure they adequately capture key attributes needed to support decision making.  


## AREAS OF POTENTIAL FUTURE WORK  

- *Develop a Fraser Pink salmon life cycle model.* Outmigrating Fraser Pink fry abundance has been enumerated near Mission since 1984, and coarse methods have been used to estimate annual migration. 
Development of a life cycle model that partitions freshwater and marine dynamics, and explicitly accounts for changing reproductive potential (due to declines in body size, changing marine survival or egg to fry survival), would enable more explicit consideration of ecosystem and climate drivers of stock dynamics and enable them to be accounted for when estimating benchmarks and assessing stock status. 
When used to condition the biological sub-model in the closed loop simulations, these drivers of life stage specific dynamics could then be explicitly accounted for when evaluating HCR performance.
Adding time-varying productivity or trending marine survival, then pairing these with environmental data, will allow us to explore which processes are influenceing survival at certain stages. 

-	*Improve understanding of changes in spatial distribution of adult spawners.* 
The last detailed assessment of changes in the spatial distribution Fraser Pink salmon was conducted by @pessInfluencePopulationDynamics2012 with tributary level data through 1947-87. 
Since that time there has not been formal tributary level assessment of spawner abundance, but there has been anecdotal evidence of continued changes in the spatial distribution of spawning Pink salmon. 
This information could be compiled, along with observations from assessment projects focused on other species, to critically re-examine our understanding of spatial dynamics of Fraser Pink salmon and their implication for stock status and expectations of future production.  
Emerging methods using eDNA could be an efficient way to gather this information, and a funding application is in development by the authors.  

- *Adapt closed-loop simulation model to better capture contemporary fishery dynamics.* 
The fishery sub-model we developed is extremely simple and does not capture a number of potentially important process that have the potential to influence fishery outcomes. 
This includes the influence of other, non-target, species like Fraser sockeye salmon whose depressed abundance in recent years has led to restrictions on fisheries targeting co-migrating Fraser Pink salmon. 
These weak stock fishery restrictions mean that our characterization of the biological and fishery performance of the current HCR may be pessimistic when it comes to conservation risk, and optimistic when it comes to fishery performance. 
A multi-species Operating Model in our closed loop simulations that explicitly or implicitly incorporates contemporary Fraser Sockeye dynamics, and revised fishery sub-model that takes at-risk sockeye considerations into account, could be developed to enable more realistic evaluation of HCR performance.  
