# STRUCTURE ET RÉPARTITION DES STOCKS  

Le saumon rose du Fraser fraye principalement dans la partie inférieure du bassin du Fraser, en aval du canyon du Fraser et de Hells Gate (Figure \@ref(fig:fig-map)). 
Cependant, une grande composante du stock remonte dans la rivière Thompson et le complexe Seton-Anderson. Avant le glissement de terrain à Hells Gate en 1914, la majeure partie de la remonte du saumon rose du Fraser revenait et frayait dans le haut Fraser [@pessInfluencePopulationDynamics2012]. 
Bien que l’on manque de données sur l’abondance au niveau des affluents dans les dernières décennies pour le saumon rose du Fraser, les observations d’évaluation d’autres espèces ont constamment mentionné des saumons roses dans les rivières Quesnel, Chilcotin et Nechako. En 2019, le MPO a été avisé d’un glissement de terrain dans le moyen Fraser, près de Big Bar. Le saumon rose faisait partie des espèces dont la montaison était retardée par ce glissement de terrain. Les efforts d’atténuation du glissement ont été largement couronnés de succès et des saumons roses se trouvaient dans la rivière Nechako en amont du glissement en 2023 (R. Martin, MPO, Kamloops, Colombie-Britannique, comm. pers.).

On suppose que les saumons roses du Fraser composent une seule unité de conservation [@holtbyConservationUnitsPacific2008]. 
Cependant, il existe des preuves de différences dans le cycle biologique des saumons roses qui frayent en amont et en aval de Hells Gate. Par exemple, les saumons roses provenant de l’amont de Hells Gate ont des vitesses de nage maximales plus élevées, qui leur permettent de franchir les rapides de Hells Gate [@rickerHistoryPresentState1989; @williams1983EarlyRun1986] et pourraient s’expliquer par des différences génétiques [@beachamVariationBodySize1988]. De plus, la montaison des saumons roses remontant dans les zones en amont et en aval de Hells Gate est légèrement différente, comme l’a démontré un échantillonnage récent d’identification génétique des stocks dans les pêches d’essai du bas Fraser (S. Latham, CSP, Vancouver, Colombie-Britannique, comm. pers.). Ces différences permettent de penser qu’il pourrait y avoir plus de différences génétiques et de cycle biologique entre les populations reproductrices en amont et en aval de Hells Gate qu’on ne le pensait auparavant. Le Comité sur la situation des espèces en péril au Canada (COSEPAC) examine actuellement la structure des populations de saumons roses au Canada, notamment dans le Fraser (B. Leaman, COSEPAC, Duncan, Colombie-Britannique, comm. pers.).
