# FACTEURS ÉCOSYSTÉMIQUES ET CLIMATIQUES AYANT UNE INCIDENCE SUR LE STOCK  

En raison de leurs vastes migrations dans les milieux marins et d’eau douce, les saumons roses du Fraser interagissent avec un large éventail de conditions écosystémiques et climatiques tout au long de leur cycle biologique. Les habitats d’eau douce que le saumon rose du fleuve Fraser utilise pour la fraie et l’incubation sont largement répartis dans le bassin du fleuve (Figure \@ref(fig:fig-map)). La plus grande partie de la production de saumon rose a lieu dans le bas Fraser, du canyon du Fraser vers l’aval, et les habitats de cette région sont relativement fortement touchés par les activités anthropiques.

Le saumon rose a un profil aérobie et un rendement cardiovasculaire exceptionnels qui, selon les hypothèses, contribuent à sa résilience au réchauffement des eaux douces [@clarkExceptionalAerobicScope2011]. 
Cependant, en raison de sa taille relativement petite, il est particulièrement vulnérable aux répercussions liées au débit pendant les montaisons en eau douce. Les impacts du début de la construction du chemin de fer à Hells Gate dans les années 1880 (c.-à-d. l’immersion de roches dans la rivière), de la construction du nouveau chemin de fer en 1913 et du glissement rocheux subséquent en 1914, ont créé des obstacles hydrologiques qui ont considérablement limité la montaison du saumon rose vers ses lieux de fraie dans le haut Fraser. 
Après l’observation d’une population nombreuse de saumons rouges apparemment coincée en aval du glissement en 1941, des installations de passage du poisson ont été construites en 1944 et ont restauré la montaison et rétabli des populations reproductrices dans le haut Fraser [@roosRestoringFraserRiver1991]. 
Le glissement rocheux de 2018-2019 à Big Bar dans le canyon du Fraser, plus en amont de Hells Gate, a créé un autre obstacle partiel à la montaison, pendant les périodes de débit élevé, vers les lieux de fraie des eaux d’amont.

En plus des répercussions liées au débit sur la migration des adultes, les débits extrêmes (p. ex. à la suite de pluies automnales) peuvent causer une mortalité élevée au stade de l’œuf à l’alevin du saumon du Pacifique résultant de l’affouillement des nids où les œufs incubent [@montgomeryStreambedScourEgg1996]. 
Malgré les débits extrêmes et les inondations qui se sont produits dans le bas Fraser ces dernières années (p. ex. à l’automne 2021), peu d’études ont porté sur les impacts de ces débits extrêmes sur le succès de l’incubation du saumon rose du Fraser.

Dans le milieu marin, la survie du saumon rose du Fraser est associée négativement à des températures de la surface de la mer supérieures à la moyenne au début de la vie en mer [@mueterOppositeEffectsOcean2002], à une efflorescence printanière plus précoce [@malickEffectsNorthPacific2017], à une salinité plus élevée [@dfoPreseasonRunSize2021] et à un courant du Pacifique Nord faible [@malickEffectsNorthPacific2017]; toutes ces caractéristiques indiquent des conditions océanographiques physiques et biologiques qui ont probablement des effets sur la production, le transport et la disponibilité des proies au début de la vie en mer. De plus, l’abondance croissante des saumons du Pacifique dans l’ensemble du Pacifique Nord (dominée par le saumon rose, le saumon kéta et le saumon rouge) est associée à des déclins de la taille des saumons roses du Fraser adultes (Figure \@ref(fig:fig-avg-mass)), qui peuvent découler de la concurrence interspécifique et intraspécifique entre les saumons pour des ressources en proies limitées en mer [@ruggeroneDiatomsKillerWhales2023]. Ces baisses de la taille des géniteurs se répercutent probablement à leur tour sur le taux de reproduction puisque la fécondité est proportionnelle à la taille des femelles [@beachamFecundityEggSize1993].

Les conditions océanographiques physiques et biologiques qui influent sur la production de proies et la survie du saumon rose continueront probablement de varier à mesure que le Pacifique Nord se réchauffera sous l’effet des changements climatiques [@litzowClimateAttributionTime2024]. 
Ces variations peuvent comprendre une réduction de la production et de la disponibilité du zooplancton riche en lipides au début de la vie en mer ou un décalage accru entre le moment de l’entrée dans l’océan et la période de la productivité marine (p. ex. l’efflorescence printanière; @wilsonPhenologicalShiftsMismatch2023).
