# RÉSULTATS  

## AJUSTEMENT ET DIAGNOSTICS DU MODÈLE  
L’inspection visuelle des tracés a révélé que toutes les chaînes étaient bien mélangées pour les paramètres principaux, que tous les paramètres avaient un $\hat{R}$ < 1,01 (maximum de 1,003), que la taille effective des échantillons était > 10 % des tirages (minimum de 39 % dans un modèle variable dans le temps), dénotant une convergence raisonnable du modèle, et que des contrôles prédictifs a posteriori qui ressemblaient aux données avaient été utilisés pour ajuster le modèle. (Voir à l’annexe A des détails sur l’environnement informatique et sur la reproduction de l’analyse, ainsi qu’un lien vers un supplément décrivant les ajustements du modèle.)  


## POINTS DE RÉFÉRENCE BIOLOGIQUES, ÉTAT ET TENDANCES DES STOCKS    
Les moyennes a posteriori, les médianes et les intervalles crédibles à 80 % pour les principaux paramètres géniteurs-recrutement et les points de référence biologiques sont résumés dans le Tableau \@ref(tab:tab-bench-parms). Nous avons constaté que le stock de saumon rose du Fraser est moyennement productif, la productivité intrinsèque ($\alpha$) étant estimée à 3,94 (de 3,02 à 5,02 recrues par géniteur; intervalle médian et crédible à 80 %) et la taille du stock à l’équilibre $S_{éq}$, qui est une fonction de la productivité intrinsèque ($\alpha$) et de la force de la dépendance à la densité dans le stock ($\beta$), étant estimée à 14,1 M (de 11,41 à 18,48 M). Nous avons estimé que les anomalies du recrutement étaient faiblement corrélées positivement dans le temps, avec la valeur de $\phi$ estimée à 0,06 (de -0,09 à 0,31) sans forte tendance temporelle, bien que les quatre dernières années d’éclosion aient toutes été négatives (Figure \@ref(fig:fig-rec-resid)). Les estimations de la productivité variable selon le temps indiquent une baisse à partir des années 1980 (\@ref(fig:fig-tv-alpha)), avec la productivité médiane des trois dernières générations estimée à 2,27 (de 1,44 à 3,62).  

En raison de la faible dépendance à la densité, le rendement prévu (c.-à-d. la production « excédentaire » au-dessus du remplacement) et le recrutement étaient relativement stables avec un large éventail d’abondances des géniteurs (Figure \@ref(fig:fig-SRR)). L’abondance des géniteurs qui devrait maximiser le rendement durable à long terme (S_RMD) a néanmoins été estimée à 5,75 M, ce qui donne un PRS de 80 % de S_RMD de 4,6 M (de 3,64 à 6,11 M). Le TE, U_RMD (équation \@ref(eq:get-Umsy)), a été estimé à 0,56 (de 0,47 à 0,63) et, enfin, le PRL, S_gén, à 1,72 M (de 1,1 à 2,7 M).  

L’historique de l’état du stock de saumon rose du Fraser peut être visualisé comme une « courbe de Kobe », une façon courante de visualiser l’état du stock dans le temps par rapport aux points de référence fondés sur la biomasse (ou l’abondance) et le taux d’exploitation. La courbe de Kobe pour le saumon rose du Fraser (Figure \@ref(fig:fig-kobe)) montre que le stock avait été surexploité et l’était encore (c.-à-d. prises supérieures à $U_{RMD}$, avec des géniteurs en dessous de $S_{RMD}$) au début de la série chronologique en 1959 et que cette situation s’est généralement poursuivie jusqu’à l’adoption du régime de gestion actuel en 1987. La surpêche était peut-être due, du moins en partie, à la pêche à la traîne qui apprenait à capturer des saumons roses dans les eaux extérieures, et cette surexploitation a été reconnue en 1957 lorsque la Commission internationale des pêches du saumon du Pacifique a été chargée de gérer les pêches du saumon rose du Fraser partagées par les États-Unis et le Canada [@rickerHistoryPresentState1989]. Depuis, les prises ont diminué et le stock est remonté à des niveaux plus élevés d’abondance des géniteurs (Figure \@ref(fig:fig-catch-esc)), avec certaines années intermédiaires où le stock a été surexploité lorsque l’abondance était forte (quadrant supérieur droit, Figure \@ref(fig:fig-kobe)) et sous-pêché lorsqu’elle était faible (quadrant inférieur gauche, Figure \@ref(fig:fig-kobe)). Dans l’ensemble, la courbe de Kobe permet de penser que le stock est actuellement sous-exploité, mais il peut être difficile d’atteindre l’objectif de prise défini dans la RCP en raison d’autres considérations de gestion.  

L’observation la plus récente (2023) de l’abondance des géniteurs pour le saumon rose du Fraser est de 9,58 M, un chiffre bien au-dessus du PRS de 80 % de $S_{RMD}$, indiquant que le stock est dans un état « sain » (Figure \@ref(fig:fig-status)). Cet état sain du stock est conforme à l’outil d’évaluation rapide de la situation de la Politique concernant le saumon sauvage qui tient compte de la qualité des données et de différents paramètres [@pestalStateSalmonRapid2023] et qui a évalué le stock comme étant dans le vert avec un niveau de confiance élevé ([Supplement A](https://doi.org/10.5281/zenodo.12549905)).  

                                                                    t   
## RENDEMENT DE LA RÈGLE DE CONTRÔLE DES PRISES  

Nous avons constaté que la RCP existante pour le saumon rose du Fraser présente une très faible probabilité ($S_{gén}$, 4,28 %) que le stock tombe sous son PRL et une probabilité relativement élevée (80 % de $S_{RMD}$, 87,54 %) que l’abondance des géniteurs soit supérieure au PRS dans les 10 prochaines années (Tableau \@ref(tab:tab-HCR-performance); Figure \@ref(fig:fig-fwd-SC)). En supposant que les pêches utilisent pleinement la prise permissible, ce qui pourrait ne pas être le cas si la pêche du saumon rose est restreinte afin de limiter les répercussions sur les espèces non ciblées, la prise annuelle médiane devrait être de 10,3 millions de poissons. On prévoit que les prises seront supérieures à l’indice des « bonnes prises » (6,31 millions; un indicateur semi-arbitraire d’une « bonne année » fondé sur la moyenne des trois prises les plus importantes depuis l’an 2000) environ 64,3 % des années. En revanche, la RCP de rechange, à titre informatif, conforme à l’approche de précaution, présentait une probabilité légèrement plus élevée que le stock tombe sous le PRL (5,16 % contre 4,28 %) et donnait des résultats semblables pour l’abondance de géniteurs supérieure au PRS (87,46 % contre 87,54 %; tableau \@ref(tab:tab-HCR-performance); Figure \@ref(fig:fig-fwd-SC)). Ces risques biologiques légèrement plus grands correspondaient à 1,5 million de poissons de moins capturés selon la RCP de rechange. Comparativement à la RCP actuelle, le scénario sans pêche augmentait la probabilité d’être au-dessus du PRL et du PRS de 0,32 et de 5,6 %, respectivement (Tableau \@ref(tab:tab-HCR-performance); Figure \@ref(fig:fig-fwd-SC)).  

Le rendement dans le scénario de faible productivité, où la productivité récente était ramenée à son 10e centile inférieur, a montré que les différentes RCP ont un rendement relativement semblable, mais avec un risque biologique accru et moins de prises. Le pourcentage de simulations inférieures à $S_{gén}$ ou supérieures à 80 % de $S_{RMD}$ a passé à environ 15 % de plus de zones plus risquées, avec des prises inférieures à la moitié de ce qu’elles étaient dans le scénario de base (Tableau \@ref(tab:tab-HCR-performance)). La RCP de rechange avait un rendement relativement pire que la RCP actuelle dans le scénario de faible productivité. Avec la RCP de rechange, le nombre de simulations avec une abondance de géniteurs inférieure à $S_{gén}$ a quadruplé et le nombre de simulations avec une abondance de géniteurs supérieure à 80 % de $S_{RMD}$ a été réduit à 72 % du nombre dans le scénario de base, alors qu’avec la RCP actuelle, le nombre en dessous de$S_{gén}$ est doublé et le nombre de simulations au-dessus de $S_{RMD}$ est réduit de 84 %.  
