# DISCUSSION  

## SOMMAIRE DES PRINCIPALES CONSTATATIONS    

Dans ce document de recherche, nous examinons brièvement notre compréhension actuelle de la structure et de la répartition des stocks de saumon rose du fleuve Fraser, l’historique de l’évaluation et les facteurs écosystémiques et climatiques qui ont une incidence sur les stocks. Nous avons ensuite ajusté un modèle géniteurs-recrutement de type état-espace aux données disponibles afin de caractériser la dynamique des stocks et d’estimer des points de référence biologiques pour évaluer l’état des stocks. Nous avons enfin élaboré un modèle simple de simulation en boucle fermée fondé sur des estimations récentes de la productivité afin de quantifier le rendement biologique et halieutique futur prévu de la règle actuelle de contrôle des prises (RCP), d’une autre RCP à titre indicatif et d’un scénario sans pêche.  

Les saumons roses du Fraser des années impaires frayent dans tout le bassin du Fraser et constituent une seule unité de conservation, bien qu’il y ait des preuves de différences dans le cycle biologique entre les populations qui frayent dans le haut Fraser et le bas Fraser (en amont et en aval de Hells Gate). Des glissements de terrain se sont produits dans tout le Fraser et ont causé des obstacles à la montaison des adultes à différentes périodes, le plus notable étant celui de Hells Gate en 1914 et, plus récemment, le glissement de terrain de Big Bar en 2018-2019. La survie en mer du saumon rose du Fraser est associée à la température de la surface de la mer au début de la vie marine, au moment de l’efflorescence printanière et au courant du Pacifique Nord, qui sont tous des indices de conditions océanographiques physiques et biologiques qui ont probablement des effets sur la production, le transport et la disponibilité des proies au début de la vie en mer. La taille des adultes a diminué au fil du temps, ce qui coïncide avec l’augmentation de l’abondance des saumons dans le Pacifique Nord, qui pourrait avoir une incidence sur le taux de reproduction puisque la fécondité est proportionnelle à la taille des femelles.  

Nous avons constaté que le stock de saumon rose du Fraser est modérément productif, avec une productivité intrinsèque ($\alpha$) estimée à 3,94 (de 3,02 à 5,02 recrues par géniteur) et un stock à l’équilibre $S_{éq}$ égal à 14,1 M (de 11,41 à 18,48 M). Nous avons estimé que le PRS de 80 % de $S_{RMD}$ s’établit à 4,6 M (de 3,64 à 6,11 M) et que le point de référence limite S_gén est de 1,72 M (de 1,1 à 2,7 M). L’observation la plus récente (2023) de l’abondance des géniteurs pour le saumon rose du Fraser est de 9,58 M, un chiffre bien au-dessus du 90e centile de l’estimation du PRS; on en déduit que le stock est « sain », ce qui est conforme à l’outil d’évaluation rapide de la situation de la Politique concernant le saumon sauvage, qui a évalué le stock comme étant dans la zone d’état « verte » de cette Politique avec un degré de confiance élevé.  

Un modèle de productivité variable dans le temps utilisé pour conditionner la simulation prospective a montré que la productivité des saumons roses du Fraser diminue depuis les années 1980, ce qui coïncide à peu près avec le début du déclin de la taille moyenne des adultes en montaison. La productivité des dernières années est proche de la moitié de ce qu’elle était à son pic dans les années 1980.  

Nous avons constaté que la RCP existante pour le saumon rose du Fraser présente une très faible probabilité (< 4,28 %) que le stock tombe sous son point de référence limite et une probabilité relativement élevée (87,5 %) que l’abondance des géniteurs soit supérieure au PRS dans les 10 prochaines années. En supposant que les pêches utilisent pleinement la prise permissible, ce qui pourrait ne pas être le cas si la pêche du saumon rose est restreinte afin de, par exemple, limiter les répercussions sur les espèces non ciblées, la prise annuelle moyenne devrait être de 10,3 M sur la même période. L’évaluation d’une autre RCP à titre indicatif, qui est strictement conforme au Cadre de l’approche de précaution du MPO, a donné un rendement biologique semblable pour une prise légèrement inférieure. Comparativement à la RCP existante, un scénario sans pêche indiquait que 0,3 % et 5,6 % des simulations étaient supérieures au PRL et au PRS, respectivement.  

D’après le test de robustesse de l’actuelle RCP, si la productivité des stocks devait chuter fortement ou être déprimée pendant une période prolongée, la RCP actuelle aurait une probabilité d’environ 5 % plus élevée de tomber en dessous du PRL, une probabilité d’environ 14 % plus grande de tomber en dessous du PRS dans la zone « ambre » et environ 7 M de poissons de moins capturés que dans le scénario de référence. La RCP de rechange, strictement conforme à l’AP, donnait des résultats relativement pires que la RCP actuelle dans le test de robustesse, peut-être en raison des taux d’exploitation plus élevés autorisés pour des remontes intermédiaires. Pour atténuer ces risques, une option à explorer à l’avenir pourrait être d’utiliser une version dynamique de notre RCP de rechange, dans laquelle le taux d’exploitation de référence $U_{RMD}$ varie en fonction des estimations actuelles de la productivité variable dans le temps.  

In this research document we briefly review our current understanding of Fraser River Pink Salmon stock structure and distribution, assessment history, and ecosystem and climate factors affecting the stock. 
We then fit a state-space spawner-recruitment model to available to data to characterize stock dynamics, and derive estimates of biological benchmarks to assess stock status. 
Lastly, we developed a simple closed-loop simulation model based on recent productivity estimates to quantify future expected biological and fishery performance of the current, an illustrative alternative HCR, and a no fishing scenario.  

Odd year Fraser Pinks spawn throughout the Fraser Basin and comprise a single Conservation Unit though there is evidence of life history differences between populations that spawn in the upper and lower Fraser River (above and below Hells Gate). 
Landslides have occurred throughout the Fraser causing migratory impediments that have impacted returning adult salmon at different periods with the most notable being Hells Gate in 1914 and more recently the Big Bar Landslide in 2018/19. 
Fraser Pink Salmon marine survival is associated with sea-surface temperatures during early marine life, spring bloom timing and the North Pacific Current, all of which index physical and biological oceanographic conditions that likely affect prey production, transport, and availability during early marine life. 
Adult body size has declined over time, coincident with increasing abundances of salmon in the North Pacific, which has the potential to impact reproductive output as fecundity scales with female size. 

## MISES EN GARDE ET HYPOTHÈSES  
Les mesures du rendement des simulations prospectives doivent être interprétées avec prudence pour plusieurs raisons. Premièrement, nos mesures de rendement sont calculées pour l’ensemble des cinq générations de simulations et ne reflètent donc pas un rendement à court terme plus précis, comme le montrent les figures des trajectoires (p. ex. la prise médiane relativement plus élevée avec la RCP actuelle pourrait être attribuable à un gain à court terme dans les prises en 2025). Deuxièmement, nous avons posé l’hypothèse simplificatrice selon laquelle l’erreur de prévision et l’incertitude des résultats avaient une distribution log-normale et normale entre les remontes, respectivement. Lorsque l’on prévoit des remontes faibles, il se peut qu’il n’y ait pas de données supplémentaires sur la pêche commerciale pour étayer les ajustements en cours de saison [@hagueImprovementsFraserRiver2022]. La petite taille des échantillons dans les prises de saumon rose pourrait également transmettre l’incertitude par les diverses méthodes d’estimation de la taille des stocks : pêches d’essai, analyses de la CPUE, identification génétique des stocks et programme hydroacoustique [@hagueMovingTargetsAssessing2021]. La petite taille de l’échantillon et le faible effort de pêche peuvent exacerber l’erreur de prévision lorsque la remonte est peu nombreuse, risquant de contredire notre hypothèse selon laquelle l’erreur de prévision est constante entre les remontes. Troisièmement, l’incertitude des résultats (c.-à-d. la mesure dans laquelle vous vous rapprochez du taux d’exploitation cible) peut être inférieure à celle prévue pour des raisons de gestion pratique (p. ex. réduction de l’effort de pêche du saumon rose pour protéger les populations de saumons rouges en péril). De plus, le prix du saumon rose est si bas ces dernières années que cette exploitation n’est peut-être pas économiquement viable pour les pêcheurs commerciaux. Ensemble, ces raisons pour réduire l’effort de pêche peuvent fausser vers la droite la forme de l’incertitude réelle des résultats, étant donné que les pêches ne capturent généralement pas leur total autorisé des captures. Il est donc important de considérer les valeurs du Tableau \@ref(tab:tab-HCR-performance)comme des mesures du rendement relatives et non absolues; les prises pourraient ne pas être réalisées en raison de divers facteurs de gestion.


## CIRCONSTANCES EXCEPTIONNELLES OU DÉCLENCHEURS D’ÉVALUATION POUR LE STOCK    
Les circonstances exceptionnelles sont des déclencheurs d’évaluation visant à déterminer de façon proactive les conditions ou les circonstances qui peuvent représenter un écart important par rapport à celles en vertu desquelles l’avis présenté dans la présente évaluation a été élaboré (c.-à-d. réévaluer les hypothèses du modèle). En plus d’une réévaluation de routine toutes les deux générations pour actualiser l’état des stocks et tenir compte des processus halieutiques et biologiques contemporains, nous recommandons de déclencher une réévaluation si l’un des événements suivants se produit :

-	La productivité des stocks change radicalement, l’estimation médiane de la productivité variable dans le temps ($\alpha$ annuel de Ricker) se situe à l’extérieur du 50e centile (de 1,8 à 2,93) de la productivité médiane sur trois générations utilisée pour conditionner notre simulation prospective;

-	De nouveaux renseignements disponibles entraînent des variations dans les séries chronologiques historiques de l’abondance des géniteurs et des prises utilisées dans le présent document de recherche;

-	De nouveaux renseignements disponibles modifient notre compréhension de la structure des stocks (p. ex. l’unité de conservation actuelle est divisée en deux) ou des facteurs importants de la dynamique des stocks.
Enfin, si la Direction de la gestion des pêches envisage de modifier la RCP existante ou de réviser les objectifs de pêche par rapport auxquels elle doit être évaluée, il faudra revoir le modèle d’évaluation et le cadre de simulation en boucle fermée que nous décrivons pour vérifier qu’ils reflètent adéquatement les attributs clés nécessaires pour étayer la prise de décisions.


## DOMAINES DE TRAVAIL FUTURS POSSIBLES  

-	*Élaborer un modèle de cycle biologique du saumon rose du Fraser*. Depuis 1984, l’abondance des alevins roses du Fraser est dénombrée près de Mission et des méthodes grossières ont été utilisées pour estimer la migration annuelle. L’élaboration d’un modèle du cycle biologique qui répartit la dynamique dans l’eau douce et en mer et tient compte explicitement de l’évolution du potentiel de reproduction (en raison de la diminution de la taille, de la modification de la survie en mer ou de la survie de l’œuf à l’alevin) permettrait une prise en compte plus explicite des facteurs écosystémiques et climatiques de la dynamique des stocks et leur intégration dans l’estimation des points de référence et l’évaluation de l’état des stocks. Lorsqu’ils sont utilisés pour conditionner le sous-modèle biologique dans les simulations en boucle fermée, ces facteurs de la dynamique propre à chaque stade biologique peuvent ensuite être pris en compte explicitement dans l’évaluation du rendement de la RCP. L’ajout d’une productivité variable dans le temps ou des tendances de la survie en mer, puis l’association de ces éléments avec des données environnementales, nous permettra d’explorer les processus qui influent sur la survie à certains stades.  

-	*Améliorer la compréhension des changements dans la répartition spatiale des géniteurs adultes*. La dernière évaluation détaillée des changements dans la répartition spatiale du saumon rose du Fraser a été effectuée par @pessInfluencePopulationDynamics2012 avec les données au niveau des affluents de 1947 à 1987. Depuis, il n’y a pas eu d’évaluation officielle de l’abondance des géniteurs au niveau des affluents, mais on dispose de preuves anecdotiques de changements continus de la répartition spatiale des saumons roses reproducteurs. Cette information pourrait être compilée, avec les observations de projets d’évaluation axés sur d’autres espèces, afin de réexaminer de façon critique notre compréhension de la dynamique spatiale du saumon rose du Fraser et de ses répercussions sur l’état des stocks et les attentes en matière de production future.  

-	*Adapter le modèle de simulation en boucle fermée pour mieux refléter la dynamique contemporaine de la pêche*. Le sous-modèle halieutique que nous avons élaboré est extrêmement simple et ne reflète pas un certain nombre de processus potentiellement importants qui pourraient avoir une incidence sur les résultats des pêches, notamment l’influence d’autres espèces non ciblées, comme le saumon rouge du Fraser, dont l’abondance réduite ces dernières années a entraîné des restrictions sur les pêches ciblant le saumon rose du Fraser qui migre en même temps. Ces restrictions des pêches de stocks faibles signifient que notre caractérisation du rendement biologique et halieutique de la RCP actuelle peut être pessimiste en ce qui concerne le risque de conservation et optimiste en ce qui concerne le rendement des pêches. Un modèle opérationnel plurispécifique dans nos simulations en boucle fermée, qui intègre explicitement ou implicitement la dynamique contemporaine du saumon rouge du Fraser, et un sous-modèle halieutique révisé qui tient compte des facteurs du saumon rouge en péril, pourrait être mis au point pour permettre une évaluation plus réaliste du rendement de la RCP.  
